---
- name: Check if installed
  stat: path="/Applications/Sublime Text.app"
  register: sublimetext_installed

- debug: msg="Sublime Text is already installed. Skipping..."
  when: sublimetext_installed.stat.exists == True

- name: Download
  get_url: url=http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%20Build%203059.dmg
           dest=/tmp/sublimetext.dmg
  when: sublimetext_installed.stat.exists == False

- name: Mount
  command: hdiutil attach sublimetext.dmg chdir=/tmp
  when: sublimetext_installed.stat.exists == False

- name: Copy to Applications
  command: cp -R /Volumes/Sublime\ Text/Sublime\ Text.app /Applications
  when: sublimetext_installed.stat.exists == False

- name: Unmount
  command: hdiutil detach /Volumes/Sublime\ Text
  when: sublimetext_installed.stat.exists == False

- name: Copy Fonts
  copy: src="../files/{{ item }}.ttf"
        dest="~/Library/Fonts/{{ item }}.ttf"
  with_items:
    - "Anonymous Pro B"
    - "Anonymous Pro BI"
    - "Anonymous Pro I"
    - "Anonymous Pro"

- name: Copy Config
  copy: src=../files/config
        dest="~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings"
